package com.orangehrm.pages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import com.orangehrm.actiondriver.ActionDriver;
import com.orangehrm.base.BaseClass;

public class PIMPage {

	private ActionDriver actionDriver;

	// Locators below were verified directly against the live DOM via
	// browser console before being written here (see project history) -
	// not assumed from typical OrangeHRM markup.

	private By addEmployeeTab = By.xpath("//a[contains(normalize-space(.),'Add Employee')]");

	// First/Middle/Last Name all have real name attributes - far more
	// reliable than label-chasing XPath.
	private By firstNameInput = By.name("firstName");
	private By middleNameInput = By.name("middleName");
	private By lastNameInput = By.name("lastName");

	// Employee Id has no name attribute but does have an associated label,
	// found the same ancestor-based way that worked for the Admin page.
	private static final String INPUT_GROUP_ANCESTOR = "ancestor::div[contains(concat(' ',normalize-space(@class),' '),' oxd-input-group ')][1]";
	private By employeeIdInput = By.xpath("//label[contains(text(),'Employee Id')]/" + INPUT_GROUP_ANCESTOR + "//input");
	private By driversLicenseInput = By.xpath("//label[contains(text(),\"Driver's License Number\")]/" + INPUT_GROUP_ANCESTOR + "//input");

	private By saveButton = By.xpath("//button[contains(normalize-space(.),'Save')]");

	// After Save, OrangeHRM redirects to .../pim/viewPersonalDetails/empNumber/{id}
	// and shows the employee's full name in a div with this real, unique class.
	private By employeeNameHeading = By.xpath("//div[contains(concat(' ',normalize-space(@class),' '),' orangehrm-edit-employee-name ')]");

	public PIMPage(WebDriver driver) {
		this.actionDriver = BaseClass.getActionDriver();
	}

	// Navigates from the Employee List page (where clicking the PIM nav
	// item lands you) to the Add Employee form.
	public void clickAddEmployeeTab() {
		actionDriver.click(addEmployeeTab);
	}

	// Fills in the Add Employee form (Employee Id is auto-generated by
	// OrangeHRM and left as-is unless overridden) and clicks Save. Assumes
	// clickAddEmployeeTab() has already been called.
	public void addEmployee(String firstName, String middleName, String lastName) {
		actionDriver.enterText(firstNameInput, firstName);
		if (middleName != null && !middleName.isEmpty()) {
			actionDriver.enterText(middleNameInput, middleName);
		}
		actionDriver.enterText(lastNameInput, lastName);
		actionDriver.click(saveButton);
	}

	// Returns the auto-generated (or entered) Employee Id shown on the form
	// before Save is clicked.
	public String getEmployeeId() {
		return actionDriver.getText(employeeIdInput);
	}

	// True once the personal details page has loaded after a successful
	// save - blocks until the URL actually changes (rather than checking
	// once immediately, which races the browser's redirect) and throws a
	// clear TimeoutException if the redirect never happens within the wait
	// window.
	public boolean isOnPersonalDetailsPage() {
		actionDriver.waitUntilUrlContains("viewPersonalDetails/empNumber/");
		return actionDriver.getCurrentUrl().contains("viewPersonalDetails/empNumber/");
	}

	// Verifies the saved employee's full name is shown on the resulting
	// Personal Details page. Uses getText() + a normalized-whitespace
	// comparison rather than ActionDriver.compareText()'s strict equals(),
	// since we've already been caught out once by unexpected extra
	// whitespace in real page text (see AdminUserManagementPage history).
	public boolean verifyEmployeeNameOnDetailsPage(String expectedFullName) {
		String actualText = actionDriver.getText(employeeNameHeading);
		String normalizedActual = actualText.trim().replaceAll("\\s+", " ");
		String normalizedExpected = expectedFullName.trim().replaceAll("\\s+", " ");
		return normalizedActual.equals(normalizedExpected);
	}

	// ---- My Info / Personal Details: Driver's License Number ----
	// (My Info routes into this exact same page, scoped to the logged-in
	// user's own record.)
	public void updateDriversLicenseNumber(String licenseNumber) {
		actionDriver.enterText(driversLicenseInput, licenseNumber);
		actionDriver.click(saveButton);
		actionDriver.waitForInvisibility(By.className("oxd-toast-container"));
	}

	public String getDriversLicenseNumber() {
		return actionDriver.getInputValue(driversLicenseInput);
	}

	// ---- Employee List / Search ----
	// Verified via console: the Employee Name search field on the Employee
	// List page uses the identical oxd-input-group structure as other
	// fields on this site, so it reuses INPUT_GROUP_ANCESTOR.
	private By searchEmployeeNameInput = By.xpath("//label[contains(text(),'Employee Name')]/" + INPUT_GROUP_ANCESTOR + "//input");
	private By searchButton = By.xpath("//button[contains(normalize-space(.),'Search')]");
	// NOTE: this reuses the oxd-autocomplete-option pattern verified on the
	// Admin User Management page, on the assumption OrangeHRM reuses the
	// same Vue autocomplete component across the site (it's the same
	// "Type for hints..." widget). Not independently re-verified for this
	// page - if selecting a suggestion fails here, this is the first place
	// to check.
	private By resultsTableBody = By.className("oxd-table-body");

	public void searchEmployeeByName(String partialName, String fullNameToSelect) {
		actionDriver.enterText(searchEmployeeNameInput, partialName);
		By suggestionOption = By.xpath("//div[contains(concat(' ',normalize-space(@class),' '),' oxd-autocomplete-option ')][contains(normalize-space(.),'"
				+ fullNameToSelect + "')]");
		actionDriver.click(suggestionOption);
		actionDriver.click(searchButton);
	}

	// Checked via the results table's overall text content rather than
	// precise cell indexing, since column layout can vary. Whitespace is
	// stripped entirely (not just normalized) on both sides before
	// comparing: adjacent table cells (e.g. firstName + lastName) were
	// confirmed via console to concatenate with NO space between them in
	// raw textContent, even though they display with visual spacing via
	// CSS - a plain "first last" expected string would never match that.
	public boolean verifySearchResultContainsEmployee(String fullName) {
		String actualNoSpaces = actionDriver.getText(resultsTableBody).replaceAll("\\s+", "");
		String expectedNoSpaces = fullName.replaceAll("\\s+", "");
		return actualNoSpaces.contains(expectedNoSpaces);
	}
}