services:
  mysql:
    image: mysql:8.0
    container_name: orangehrm-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: orangehrm
    volumes:
      - orangehrm_db_data:/var/lib/mysql

  orangehrm:
    image: orangehrm/orangehrm:latest
    container_name: orangehrm-app
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      ORANGEHRM_DATABASE_HOST: mysql
      ORANGEHRM_DATABASE_USER: root
      ORANGEHRM_DATABASE_PASSWORD: ""
      ORANGEHRM_DATABASE_NAME: orangehrm
    volumes:
      - orangehrm_app_data:/orangehrm

volumes:
  orangehrm_db_data:
  orangehrm_app_data: